[project]
name = "modular-credential-nfts-academy"
description = "Smart contracts for modular credential NFTs on Stacks"
authors = ["Modular NFT Academy Team <developer@modular-nft-academy.com>"]
telemetry = false
cache_dir = ".clarinet"

[contracts.module-nft]
path = "contracts/module-nft.clar"
clarity_version = 2
epoch = "2.4"

[contracts.degree-sbt]
path = "contracts/degree-sbt.clar"
clarity_version = 2
epoch = "2.4"

[contracts.nft-trait]
path = "contracts/traits/nft-trait.clar"
clarity_version = 2
epoch = "2.4"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
